emsServers:
   - displayName: "Local EMS"
     host: "localhost"
     port: 7222
     # Supports tcp and ssl
     protocol: "tcp"
     user: "admin"
     password:
     encryptedPassword:
     encryptionKey:
     #config to show temp queues and topics
     showTemp: false
     #config to show system queues and topics
     showSystem: false
     excludeQueues: []
     excludeTopics: []
     sslIdentityFile:
     sslIdentityPassword:
     sslTrustedCerts:
     #ssl config optional settings
     sslDebug:
     sslVerifyHost:
     sslVerifyHostName:
     sslVendor:
   - displayName: "Remote EMS"
     host: "localhost"
     port: 7222
     # Supports tcp and ssl
     protocol: "tcp"
     user: "admin"
     password:
     encryptedPassword:
     encryptionKey:
     #config to show temp queues and topics
     showTemp: false
     #config to show system queues and topics
     showSystem: false
     excludeQueues: []
     excludeTopics: []


# number of concurrent tasks
numberOfThreads: 1

#This will create this metric in all the tiers, under this path. Please make sure to have a trailing |
#metricPrefix: "Custom Metrics|Tibco EMS|"

#This will create it in specific Tier aka Component. Replace <COMPONENT_ID>. Please make sure to have a trailing |.
#To find out the COMPONENT_ID, please see the screen shot here https://docs.appdynamics.com/display/PRO42/Build+a+Monitoring+Extension+Using+Java
metricPrefix: "Server|Component:<COMPONENT_ID>|Custom Metrics|Tibco EMS|"